// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saxxgkthplbcncgcfgfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheHhna3RocGxiY25jZ2NmZ2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTE1OTAsImV4cCI6MjA2MTM2NzU5MH0.T0jXF5t56xwLkmB-jES9ed0IyUiq68d4UxQ5nRB5pJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);